[package]
name = "vanadinite"
version = "0.1.0"
authors = ["Wesley Norris <repnop@outlook.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
lazy_static = { version = "1", features = ["spin_no_std"] }
log = "0.4"
spin = "0.5"
static_assertions = "1"
tinyvec = "0.3"