[config]
default_to_workspace = false

[tasks.build-vanadinite.env]
RUSTFLAGS = "-C link-arg=-Tvanadinite/lds/virt.lds -C code-model=medium"
CARGO_FEATURE_VIRT = ""

[tasks.build-vanadinite]
command = "cargo"
args = ["build", "-p", "vanadinite", "--release", "--target", "riscv64gc-unknown-none-elf", "--manifest-path", "src/Cargo.toml"]

[tasks.build-bbl]
dependencies = ["build-vanadinite"]
script = ['''
    git submodule update --init --quiet
    mkdir -p submodules/riscv-pk/build
    cd submodules/riscv-pk/build
    ../configure --host=riscv64-unknown-elf --with-payload=../../../src/target/riscv64gc-unknown-none-elf/release/vanadinite --silent
    make --silent
''']

[tasks.run]
dependencies = ["build-bbl"]
command = "qemu-system-riscv64"
args= [
    "-machine", "virt",
    "-cpu", "rv64",
    "-smp", "1",
    "-m", "128M",
    "-bios", "opensbi-riscv64-virt-fw_jump.bin",
    "-kernel", "src/target/riscv64gc-unknown-none-elf/release/vanadinite",
    #"-kernel", "submodules/riscv-pk/build/bbl",
    "-serial", "mon:stdio",
    "-nographic",
]

[tasks.debug]
dependencies = ["build-bbl"]
command = "qemu-system-riscv64"
args= [
    "-machine", "virt",
    "-cpu", "rv64",
    "-smp", "1",
    "-m", "128M",
    "-bios", "opensbi-riscv64-virt-fw_jump.bin",
    #"-kernel", "submodules/riscv-pk/build/bbl",
    "-kernel", "src/target/riscv64gc-unknown-none-elf/release/vanadinite",
    "-monitor", "stdio",
    "-gdb", "tcp::1234",
    "-S",
    "-d", "guest_errors,trace:riscv_trap,trace:sifive_gpio_write,trace:pmpcfg_csr_write,trace:pmpaddr_csr_write",
    "-D", "qemu.log",
]

[tasks.gdb]
command = "riscv64-unknown-elf-gdb"
args = [
    "src/target/riscv64gc-unknown-none-elf/release/vanadinite",
    "--eval-command", "target remote :1234",
    #"--eval-command", "c",
    #"--eval-command", "set $pc += 2",
    "--eval-command", "break *0x80200000"
]

[tasks.lldb]
command = "lldb"
args = [
    "target/riscv64gc-unknown-none-elf/release/vanadinite",
    #"--eval-command", "target remote :1234",
    #"--eval-command", "c",
    #"--eval-command", "set $pc += 2",
    #"--eval-command", "break *0x80200000"
]
