[config]
default_to_workspace = false

[env]
MACHINE = "virt"
RAM = "512M"

[tasks.'build-vanadinite.release']
env = { RUSTFLAGS = "-C link-arg=-Tvanadinite/lds/${MACHINE}.lds -C code-model=medium" }
command = "cargo"
args = ["build", "-p", "vanadinite", "--release", "--target", "riscv64gc-unknown-none-elf", "--manifest-path", "src/vanadinite/Cargo.toml", "--features", "${MACHINE}"]

[tasks.'build-vanadinite.debug']
env = { RUSTFLAGS = "-C link-arg=-Tvanadinite/lds/${MACHINE}.lds -C code-model=medium" }
command = "cargo"
args = ["build", "-p", "vanadinite", "--release", "--target", "riscv64gc-unknown-none-elf", "--manifest-path", "src/vanadinite/Cargo.toml", "--features", "${MACHINE} debug_log"]


[tasks.run]
dependencies = ["build-vanadinite.release"]
command = "qemu-system-riscv64"
args= [
    "-machine", "${MACHINE}",
    "-cpu", "rv64",
    "-smp", "4",
    "-m", "${RAM}",
    "-bios", "opensbi-riscv64-${MACHINE}-fw_jump.bin",
    "-kernel", "src/target/riscv64gc-unknown-none-elf/release/vanadinite",
    "-serial", "mon:stdio",
    "-nographic",
]

[tasks.debug]
dependencies = ["build-vanadinite.debug"]
command = "qemu-system-riscv64"
args= [
    "-machine", "${MACHINE}",
    "-cpu", "rv64",
    "-smp", "4",
    "-m", "${RAM}",
    "-bios", "opensbi-riscv64-${MACHINE}-fw_jump.bin",
    "-kernel", "src/target/riscv64gc-unknown-none-elf/release/vanadinite",
    "-monitor", "stdio",
    "-gdb", "tcp::1234",
    "-S",
    "-d", "guest_errors,trace:riscv_trap,trace:sifive_gpio_write,trace:pmpcfg_csr_write,trace:pmpaddr_csr_write",
    "-D", "qemu.log",
]

[tasks.gdb]
command = "riscv64-unknown-elf-gdb"
args = [
    "src/target/riscv64gc-unknown-none-elf/release/vanadinite",
    "--eval-command", "target remote :1234",
]

[tasks.lldb]
command = "lldb"
args = [
    "target/riscv64gc-unknown-none-elf/release/vanadinite",
]
