[build]
target = "riscv64gc-unknown-none-elf"
rustflags = [
    "-C",
    "code-model=medium",
    "-C",
    "relocation-model=pic",
    "-C",
    "link-arg=-znognustack",
    "-C",
    "link-arg=--pie",
    "-C",
    "link-arg=--no-dynamic-linker",
]

[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
