[package]
name = "std"
version = "0.1.0"
authors = ["repnop <repnop@repnop.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libvanadinite = { path = "../../src/libvanadinite" }
rt0 = { path = "../rt0" }
