[workspace]
members = [
    "bytestream",
    "elf64",
    #"fat32",
    "libvanadinite",
    "sbi",
    "tar",
    "vanadinite",
    "vanadinite_macros",
]

[profile.release]
debug = true
lto = "fat"
codegen-units = 1
