[workspace]
members = [
    "bytestream",
    "elf64",
    "librust",
    "sbi",
    "tar",
    "vanadinite",
    "vanadinite_macros",
] #"fat32",
resolver = "2"

[profile.release]
debug = true
#lto = "fat"
#codegen-units = 1
