[package]
name = "fdt"
version = "0.1.0"
authors = ["repnop <repnop@repnop.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
cstr_core = "0.2.2"
log = "0.4.11"